Add many to many indigeneity checkboxes
bcgov/rvs pull request #22
Opened 2024-02-13 17:45 UTC by jonathan-longe

Create database migrations for a new "indigeneity_types" and "student_indigeneity" tables

Admin users can create and modify indigeneity types on the maintenance page:
![Screenshot (87)](https://github.com/bcgov/rvs/assets/25233684/c987bc79-849d-4e79-aa4b-b483bbc81ade)

When adding or editing a student's profile, users have the ability to select zero, one or more indigeneity checkboxes as appropriate:
![Screenshot (88)](https://github.com/bcgov/rvs/assets/25233684/0b54b640-782e-4c6f-87fc-d6fe32da404d)

2024-02-13 19:44 UTC, kmarshgov requested changes
indigeneity is used in ReportController. Pull down the updates and then append indigeneitytype to the student model so we can view it as a relationship under students.

2024-02-13 19:44 UTC, kmarshgov commented on Modules/Twp/Database/Migrations/2024_02_08_232612_add_student_indigeneity_table.php
You don't need id and timestamps for a pivot table

2024-02-13 19:44 UTC, kmarshgov commented on Modules/Twp/Resources/assets/js/Components/StudentEditStudentTab.vue
> +            <div class="col-md-12">
This block should be shown only if the student is a citizen

2024-02-13 19:44 UTC, kmarshgov commented on Modules/Twp/Resources/assets/js/Pages/Students.vue
> +                                    <div class="col-md-12">
This block should be shown only if the student is a citizen

2024-02-13 19:44 UTC, kmarshgov commented on Modules/Twp/Entities/IndigeneityType.php
> +    protected $table = 'indigeneity_types';
no need for $table in here.

2024-02-13 22:16 UTC, jonathan-longe commented on Modules/Twp/Http/Controllers/ReportController.php
> +            ->get(), 200);
@kmarshgov like this?

2024-02-13 23:43 UTC, kmarshgov commented on Modules/Twp/Http/Controllers/ReportController.php
> +            ->get(), 200);
You got it.

2024-02-13 23:44 UTC, kmarshgov commented on Modules/Twp/Entities/IndigeneityType.php
> +        return $this->belongsToMany(
This should be enough        return $this->belongsToMany('Modules\Twp\Entities\Student', 'indigeneity_student');

2024-02-13 23:45 UTC, kmarshgov commented on Modules/Twp/Entities/Student.php
> +        return $this->belongsToMany(
return $this->belongsToMany('Modules\Twp\Entities\IndigeneityType', 'indigeneity_student');

2024-02-13 23:46 UTC, kmarshgov commented on Modules/Twp/Database/Migrations/2024_02_08_232612_add_student_indigeneity_table.php
> +            $table->foreignId('indigeneity_id')->constrained('indigeneity_types')->onDelete('cascade');
rename indigeneity_id to indigeneity_type_id

2024-02-13 23:50 UTC, kmarshgov commented on Modules/Twp/Database/Migrations/2024_02_08_232612_add_student_indigeneity_table.php
> +            $table->foreignId('indigeneity_id')->constrained('indigeneity_types')->onDelete('cascade');
rename the file to ... create_indigeneity_type_student_table
rename the table to indigeneity_type_student and it's reference in the models

2024-02-15 17:25 UTC, kmarshgov approved these changes

2024-02-15 17:26 UTC, merged